[package]
name = "rzup"
description = "tool used to install, update, or choose a version of toolchains and utilities"
version = "0.2.1"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[package.metadata.release]
release = false

[dependencies]
anyhow = "1.0.86"
cfg-if = "1.0.0"
clap = { version = "4.5.14", features = ["derive"] }
dirs = "5.0.1"
flate2 = "1.0.31"
fs2 = "0.4.3"
lazy_static = "1.5.0"
regex = "1.10.6"
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "rustls-tls",
] }
risc0-build = { path = "../risc0/build" }
serde = { version = "1.0.204", features = ["derive"] }
tar = "0.4.41"
tempfile = "3.12.0"
termcolor = "1.4.1"
thiserror = "1.0.63"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
xz = "0.1.0"
