cache = true
exclude_all_private = true
exclude_path = ["./build", "./node_modules"]
max_cache_age = "10d"
max_redirects = 10
max_retries = 3

exclude = [
  # rate limited
  "https://epubs.siam.org/doi/10.1137/0108018",
]
